const tabsEl=document.getElementById('tabs'),framesEl=document.getElementById('frames'),address=document.getElementById('address'),form=document.getElementById('addressForm');
const tabs=new Map();let activeId=null,nextId=1;
function isUrl(v){return /^https?:\/\//i.test(v)||/^[\w.-]+\.[a-z]{2,}(\/.*)?$/i.test(v)}
function target(v){v=v.trim();if(!v)return 'https://duckduckgo.com/';if(isUrl(v))return /^https?:\/\//i.test(v)?v:'https://'+v;return 'https://duckduckgo.com/?q='+encodeURIComponent(v)}
function label(url){try{return new URL(url).hostname.replace(/^www\./,'')||'new tab'}catch{return'new tab'}}
function addTab(url='https://duckduckgo.com/'){const id=nextId++,tab=document.createElement('div'),frame=document.createElement('iframe');tab.className='tab';tab.innerHTML='<span class="tab-title">new tab</span><button class="close">×</button>';frame.className='frame';frame.allow='fullscreen';frame.src=url;tabs.set(id,{tab,frame,url});tabsEl.appendChild(tab);framesEl.appendChild(frame);tab.onclick=()=>activate(id);tab.querySelector('.close').onclick=e=>{e.stopPropagation();removeTab(id)};activate(id);return id}
function activate(id){if(!tabs.has(id))return;activeId=id;for(const[tid,x]of tabs){x.tab.classList.toggle('active',tid===id);x.frame.classList.toggle('active',tid===id)}address.value=tabs.get(id).url}
function navigate(v){if(!activeId)addTab();const u=target(v),x=tabs.get(activeId);x.url=u;x.frame.src=u;x.tab.querySelector('.tab-title').textContent=label(u);address.value=u}
function removeTab(id){const x=tabs.get(id);if(!x)return;x.tab.remove();x.frame.remove();tabs.delete(id);if(!tabs.size){addTab();return}if(activeId===id)activate([...tabs.keys()][0])}
document.getElementById('newTab').onclick=()=>addTab();document.getElementById('home').onclick=()=>navigate('https://duckduckgo.com/');document.getElementById('reload').onclick=()=>{const x=tabs.get(activeId);if(x)x.frame.src=x.frame.src};document.getElementById('back').onclick=()=>{try{tabs.get(activeId).frame.contentWindow.history.back()}catch{}};document.getElementById('forward').onclick=()=>{try{tabs.get(activeId).frame.contentWindow.history.forward()}catch{}};form.onsubmit=e=>{e.preventDefault();navigate(address.value)};addTab();
